routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
	Route::resource('ticket','TicketsController');
	Route::get('ticket/{client}/create', 'TicketsController@create')
		->name('ticket.create');
	Route::get('ticket/{ticket}/destroy', 'TicketsController@destroy')
		->name('ticket.destroy');
	Route::get('ticket/{ticket}/reprint', 'TicketsController@rePrint')
		->name('ticket.reprint');

	Route::get('ticket/qr-code/generate/{ticket}', 'TicketsController@generateQR')
		->name('ticket.generate-qr');

	Route::resource('client','ClientsController');

	//Rutas solo admin
	Route::post('ticket/{ticket}/checkin', 'TicketsController@checkin')
		->name('ticket.checkin');
	Route::get('client/{client}/destroy', 'ClientsController@destroy')
		->name('client.destroy');
	Route::get('client/{client}/active', 'ClientsController@active')
		->name('client.active');
});

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Client extends Model
{
    use SoftDeletes;
    
    protected $fillable = ['document', 'name', 'address', 'phone', 'celular', 'email',];

    protected static function boot () {
		parent::boot();
		static::creating(function (Client $client) {
			if( ! \App::runningInConsole()) {
				$client->user_id = Auth::id();
			}
		});
	}

	public function tickets()
    {
        return $this->hasMany(Ticket::class);
    }

    /*********SCOPES*******BUSQUEDAS*/

    public function scopeSearch($query, $value){
        if (trim($value) != '') {   
            return $query
            	->where('document','like',"%$value%")
            	->orWhere('email','like',"%$value%")
                ->orWhere('name','like',"%$value%");
        }
    }
    /*********SCOPES*******FIN*/

}

app/Http/Controllers/ClientsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ClientRequest;
use App\Models\Client;
use Illuminate\Http\Request;

class ClientsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = Client::oldest()
            ->search($request->get('search'))
            ->paginate(25);
        return view('clients.index')
                ->with([
                    'data' => $data
                ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ClientRequest $request)
    {
        $client = new Client();
        $client->fill($request->all());
        $client->active = ($request->has('active') && $request->active=='on')? true : false;
        $client->save();

        // Cache::forget('paper-size');
        
        flash('Creado con éxito')->success()->important();
        return redirect()->route('client.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        return view('clients.edit')
        ->with([
            'client' => $client
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ClientRequest $request, Client $client)
    {
        $client->fill($request->all());
        $client->active = $request->has('active');
        if (!$client->save()) {
            throw new HttpException(500);
        }

        flash('Actualizado con éxito')->success()->important();
        return redirect()->route('client.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        $client->delete();
        flash('Eliminado con éxito')->success()->important();
        return redirect()->route('client.index');
    }

    public function active(Client $client)
    {
        $client->active = !$client->active;
        if (!$client->save()) {
            throw new HttpException(500);
        }

        flash('Activado / Desactivado con éxito')->success()->important();
        return redirect()->route('client.index');
    }
}

resources/views/clients/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="card-header text-white bg-primary">
    Clientes
    </div>
    <div class="card-body">
        <h5 class="card-title">Nuevo cliente</h5>

        {!! Form::open(['route'=>'client.store', 'method'=>'POST', 'class'=> 'mb-5']) !!}
			<div class="row">
				<div class="col-lg-6 col-xl-5">
	                <div class="form-group">
	                    {!! Form::label('name','Nombre completo') !!}
	                    {!! Form::text('name',null,['class'=>'form-control', 'placeholder'=>'Ingrese nombre completo']) !!}
	                </div>
				</div>
				<div class="col-lg-6 col-xl-5">
	                <div class="form-group">
	                    {!! Form::label('email','Correo electronico') !!}
	                    {!! Form::email('email',null,['class'=>'form-control', 'placeholder'=>'Ingrese correo electronico']) !!}
	                </div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-6 col-xl-5">
	                <div class="form-group">
	                    {!! Form::label('document','Documento de identificacion') !!}
                    	{!! Form::text('document',null,['class'=>'form-control', 'placeholder'=>'Ingrese cedula de identidad']) !!}
	                </div>
				</div>
				<div class="col-lg-6 col-xl-5">
	                <div class="form-group">
	                    {!! Form::label('address','Direccion') !!}
                    	{!! Form::text('address',null,['class'=>'form-control', 'placeholder'=>'Ingrese direccion']) !!}
	                </div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-6 col-xl-5">
	                <div class="form-group">
	                    {!! Form::label('phone','Telefono') !!}
                    	{!! Form::text('phone',null,['class'=>'form-control', 'placeholder'=>'Ingrese telefono']) !!}
	                </div>
				</div>
				<div class="col-lg-6 col-xl-5">
	                <div class="form-group">
	                    {!! Form::label('celular','Celular') !!}
                    	{!! Form::text('celular',null,['class'=>'form-control', 'placeholder'=>'Ingrese celular']) !!}
	                </div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-6 col-xl-5">
	                <div class="form-group">
	                    <div class="custom-control custom-switch custom-control-inline custom-control-success">
	                        <input type="checkbox" class="custom-control-input" id="activo" name="active" checked>
	                        <label class="custom-control-label" for="activo">Activo</label>
                    	</div>
	                </div>
	                <div class="form-group">
	                    <a href="{{ route('client.index') }}" class='btn btn-danger' data-toggle='tooltip' data-placement='top' title='Regresar' data-original-title='Top Tooltip' role='button'> Regresar </a>
                    	<button type="submit" class="btn btn-primary">Guardar</button>
	                </div>
				</div>
			</div>
		{{ Form::close() }}
            
    </div>


    
@endsection

resources/views/clients/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="card-header text-white bg-primary">
    Clientes
    </div>
    <div class="card-body">
        <h5 class="card-title">Editar cliente</h5>

        {!! Form::open(['route'=>['client.update',$client], 'method'=>'PUT', 'class'=> 'mb-5']) !!}
			<div class="row">
				<div class="col-lg-6 col-xl-5">
	                <div class="form-group">
	                    {!! Form::label('name','Nombre completo') !!}
	                    {!! Form::text('name',$client->name,['class'=>'form-control', 'placeholder'=>'Ingrese nombre completo']) !!}
	                </div>
				</div>
				<div class="col-lg-6 col-xl-5">
	                <div class="form-group">
	                    {!! Form::label('email','Correo electronico') !!}
	                    {!! Form::email('email',$client->email,['class'=>'form-control', 'placeholder'=>'Ingrese correo electronico']) !!}
	                </div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-6 col-xl-5">
	                <div class="form-group">
	                    {!! Form::label('document','Documento de identificacion') !!}
                    	{!! Form::text('document',$client->document,['class'=>'form-control', 'placeholder'=>'Ingrese cedula de identidad']) !!}
	                </div>
				</div>
				<div class="col-lg-6 col-xl-5">
	                <div class="form-group">
	                    {!! Form::label('address','Direccion') !!}
                    	{!! Form::text('address',$client->address,['class'=>'form-control', 'placeholder'=>'Ingrese direccion']) !!}
	                </div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-6 col-xl-5">
	                <div class="form-group">
	                    {!! Form::label('phone','Telefono') !!}
                    	{!! Form::text('phone',$client->phone,['class'=>'form-control', 'placeholder'=>'Ingrese telefono']) !!}
	                </div>
				</div>
				<div class="col-lg-6 col-xl-5">
	                <div class="form-group">
	                    {!! Form::label('celular','Celular') !!}
                    	{!! Form::text('celular',$client->celular,['class'=>'form-control', 'placeholder'=>'Ingrese celular']) !!}
	                </div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-6 col-xl-5">
	                <div class="form-group">
	                    <div class="custom-control custom-switch custom-control-inline custom-control-success">
	                        <input type="checkbox" class="custom-control-input" id="activo" name="active" checked>
	                        <label class="custom-control-label" for="activo">Activo</label>
                    	</div>
	                </div>
	                <div class="form-group">
	                    <a href="{{ route('client.index') }}" class='btn btn-danger' data-toggle='tooltip' data-placement='top' title='Regresar' data-original-title='Top Tooltip' role='button'> Regresar </a>
                    	<button type="submit" class="btn btn-primary">Guardar</button>
	                </div>
				</div>
			</div>
		{{ Form::close() }}
            
    </div>


    
@endsection

resources/views/clients/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="card-header text-white bg-primary">
    Clientes
    </div>
    <div class="card-body">
        <h5 class="card-title">Listado de clientes</h5>

        <a class="btn btn-primary" href="{{ Route('client.create') }}" role="button">Nuevo</a>

        <h4 class="m-4"><strong>Filtros</strong></h4>
        {!! Form::open(['route'=>'client.index', 'method'=>'GET', 'class' => 'form-inline m-2']) !!}

        <div class="form-group mx-3 mb-2">
            {!! Form::label('search','Busqueda') !!}
            {!! Form::text('search',null,['class'=>'form-control ml-2', 'placeholder'=>'Busqueda']) !!}
        </div>
        <button type="submit" class="btn btn-primary btn-flat mb-2" data-toggle="tooltip" data-placement="top" title="Buscar"><i class="fa fa-search"></i></button>

        {!! Form::close() !!}

        <table class="table table-bordered table-striped table-vcenter">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Documento</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Email</th>
                    <th scope="col">Tlfn</th>
                    <th scope="col">Celular</th>
                    <th scope="col">Accion</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $value)
                    <tr>
                        <th scope="row">{{ $value->id }}</th>
                        <td>{{ $value->document }}</td>
                        <td>{{ $value->name }}</td>
                        <td>{{ $value->email }}</td>
                        <td>{{ $value->phone }}</td>
                        <td>{{ $value->celular }}</td>
                        <td>
                            <span class="badge badge-default">
                                <a href="{{ Route('ticket.create', $value->id) }}" class="btn btn-sm btn-success" data-toggle="tooltip" data-placement="top" title="Vender ticket" data-original-title="Top Tooltip">
                                    <i class="fa fa-chart-bar" aria-hidden="true"></i>
                                </a>

                                <a href="{{route('client.edit',$value)}}" class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top" title="Editar" data-original-title="Top Tooltip">
                                    <i class="fa fa-pencil-alt" aria-hidden="true"></i>
                                </a>

                                <a href="{{ Route('client.active',$value) }}" class="btn btn-sm btn-warning" data-toggle="tooltip" data-placement="top" title="Cambiar Status" data-original-title="Top Tooltip" onclick="return confirm('Seguro que desea deshabilitar?...')">
                                    <i class="fa fa-code-branch" aria-hidden="true"></i>
                                </a>

                                <a href="{{ Route('client.destroy',$value) }}" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top" title="Eliminar" data-original-title="Top Tooltip" onclick="return confirm('Seguro que desea eliminar?...')">
                                    <i class="fa fa-times" aria-hidden="true"></i>
                                </a>
                            </span>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        {{ $data->appends(Request::query())->links() }}
    </div>


    
@endsection