routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
	Route::resource('ticket','TicketsController');
	Route::get('ticket/{client}/create', 'TicketsController@create')
		->name('ticket.create');
	Route::get('ticket/{ticket}/destroy', 'TicketsController@destroy')
		->name('ticket.destroy');
	Route::get('ticket/{ticket}/reprint', 'TicketsController@rePrint')
		->name('ticket.reprint');

	Route::get('ticket/qr-code/generate/{ticket}', 'TicketsController@generateQR')
		->name('ticket.generate-qr');

	Route::resource('client','ClientsController');

	//Rutas solo admin
	Route::post('ticket/{ticket}/checkin', 'TicketsController@checkin')
		->name('ticket.checkin');
	Route::get('client/{client}/destroy', 'ClientsController@destroy')
		->name('client.destroy');
	Route::get('client/{client}/active', 'ClientsController@active')
		->name('client.active');
});

app/Models/Ticket.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Ticket extends Model
{
	use SoftDeletes;
	
	protected $fillable = ['client_id', 'event_id', 'user_id','method_pay_id','ticket_type_id', 'ref'];
    
    protected static function boot () {
		parent::boot();
		static::creating(function (Ticket $client) {
			if( ! \App::runningInConsole()) {
				$client->user_id = Auth::id();
			}
		});
	}

	public function client()
	{
		return $this->belongsTo(Client::class)->withDefault(new Client());
	}

	public function event()
	{
		return $this->belongsTo(Event::class)->withDefault(new Event());
	}

	public function user()
	{
		return $this->belongsTo(User::class)->withDefault(new User());
	}

	public function methodPay()
	{
		return $this->belongsTo(MethodPay::class)->withDefault(new MethodPay());
	}

	public function ticketType()
	{
		return $this->belongsTo(TicketType::class)->withDefault(new ticketType());
	}

	/*********SCOPES*******BUSQUEDAS*/

    public function scopeSearch($query, $value){
        if (trim($value) != '') {   
            return $query
            	->where('id','like',"%$value%")
            	->orWhereHas('methodPay', function($query) use ($value) {
            		$query->where('name','like',"%$value%");
            	})
            	->orWhereHas('client', function($query) use ($value) {
            		$query->where('document','like',"%$value%")
            			->orWhere('name','like',"%$value%");
            	});
        }
    }
    /*********SCOPES*******FIN*/
}

app/Models/TicketType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class TicketType extends Model
{
	protected $fillable = ['name','price'];

	protected $appends = ['full_name'];

    public function getFullNameAttribute()
    {
        return "{$this->name} (USD{$this->price})";
    }
}

app/Http/Controllers/TicketsController.php
<?php

namespace App\Http\Controllers;

use App\Exports\NewTicketExport;
use App\Http\Requests\TicketRequest;
use App\Models\Client;
use App\Models\Event;
use App\Models\MethodPay;
use App\Models\Ticket;
use App\Models\TicketType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

class TicketsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = Ticket::with(['client','event','user','methodPay'])
            ->oldest()
            ->search($request->get('search'))
            ->paginate(25);
        return view('tickets.index')
                ->with([
                    'data' => $data
                ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Client $client)
    {
        $events = Event::all();
        $methodPays = MethodPay::pluck('name','id');
        //mejorar tipo de ticket
        $ticketTypes = TicketType::select(DB::raw("concat(name,' (USD',price,')') AS name"), 'id', 'price')
            ->get();

        return view('tickets.create')
            ->with([
                'client'=>$client,
                'events'=>$events,
                'methodPays'=>$methodPays,
                'ticketTypes' => $ticketTypes
            ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TicketRequest $request)
    {
        if ($request->all()) {

        DB::beginTransaction();

            $arr = [];

            for ($i=0; $i < $request->qty; $i++) { 
                $ticket = new Ticket();
                $ticket->fill($request->all());
                $ticket->serial = $this->getSerial();
                if (!$ticket->save()) {
                    DB::rollback();
                }
                $arr[] = $ticket->load(['event']);
            }
        }
        DB::commit();
        // return (new NewTicketExport($arr,$img))->download('ticket.pdf', \Maatwebsite\Excel\Excel::DOMPDF);

        return view('pdf.new-ticket', [
            'tickets' => $arr,
        ]);




        //Enviar mail
        //Generar PDF
        return redirect()->route('ticket.generate-qr',$ticket);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $ticket = Ticket::find($id)->load(['client','event','user','methodPay','ticketType']);
        
        $events = Event::pluck('name','id');
        $methodPays = MethodPay::pluck('name','id');
        //mejorar tipo de ticket
        $ticketTypes = TicketType::select(DB::raw("concat(name,' (USD',price,')') AS name"), 'id')
            ->pluck('name','id');

        return view('tickets.show')
            ->with([
                'ticket'=>$ticket,
                'events'=>$events,
                'methodPays'=>$methodPays,
                'ticketTypes' => $ticketTypes
            ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ticket $ticket)
    {
        $ticket->delete();
        flash('Anulado con éxito')->success()->important();
        return redirect()->route('ticket.index');   
    }

    public function generateQR(Ticket $ticket)
    {
        $event = $ticket->event;
        $arr = [
            'id' => $ticket->id,
            'nombre' => $ticket->client->name,
            'cedula' => $ticket->client->document,
            'fecha_compra' => $ticket->created_at,
        ];
        return view('qrCode')
            ->with([
                'ticket' => json_encode($arr),
                'event' => $event,
            ]);
    }

    public function getSerial()
    {
        $tokens = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';

        $serial = '';

        for ($i = 0; $i < 4; $i++) {
            for ($j = 0; $j < 5; $j++) {
                $serial .= $tokens[rand(0, 35)];
            }

            if ($i < 3) {
                $serial .= '-';
            }
        }

        return $serial;
    }

    public function checkin(Request $request,$id)
    {
        $clientId = $request->client_id;
        $serial = $request->serial;
        $eventId = $request->event_id;

        $ticket = Ticket::find($id);

        if ($ticket) {
            if ($ticket->client->id == $clientId && $ticket->serial == $serial && $ticket->event->id == $eventId  ) {
                $ticket->checkin_at=\Carbon\Carbon::now();
                $ticket->save();
                return redirect()->back();
            }
        }
        return 'error';
    }

    public function rePrint($id)
    {
        $ticket = Ticket::find($id)->load(['client','event','user','methodPay','ticketType']);
        $arr[] = $ticket;

        // return (new NewTicketExport($arr))->download('ticket.pdf', \Maatwebsite\Excel\Excel::DOMPDF);
        return view('pdf.new-ticket', [
            'tickets' => $arr,
        ]);
    }
}

resources/views/tickets/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="card-header text-white bg-primary">
    Tickets
    </div>
    <div class="card-body">
        <h5 class="card-title">Vender Ticket</h5>

        {!! Form::open(['route'=>'ticket.store', 'method'=>'POST', 'class'=> 'mb-5']) !!}
			<div class="row">
				<div class="col-lg-4 col-xl-5">
					{!! Form::hidden('client_id',$client->id,[]) !!}
	                <div class="form-group">
	                    {!! Form::label('name','Nombre completo') !!}
	                    {!! Form::text('name',$client->name,['class'=>'form-control','disabled']) !!}
	                </div>
				</div>
				<div class="col-lg-4 col-xl-5">
	                <div class="form-group">
	                    {!! Form::label('email','Correo electronico') !!}
	                    {!! Form::email('email',$client->email,['class'=>'form-control', 'disabled']) !!}
	                </div>
				</div>
				<div class="col-lg-4 col-xl-2">
	                <div class="form-group">
	                    {!! Form::label('document','Documento de identificacion') !!}
                    	{!! Form::text('document',$client->document,['class'=>'form-control', 'disabled']) !!}
	                </div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-4 col-xl-5">
	                <div class="form-group">
	                    {!! Form::label('address','Direccion') !!}
                    	{!! Form::text('address',$client->address,['class'=>'form-control', 'disabled']) !!}
	                </div>
				</div>
				<div class="col-lg-4 col-xl-5">
	                <div class="form-group">
	                    {!! Form::label('phone','Telefono') !!}
                    	{!! Form::text('phone',$client->phone,['class'=>'form-control', 'disabled']) !!}
	                </div>
				</div>
				<div class="col-lg-4 col-xl-2">
	                <div class="form-group">
	                    {!! Form::label('celular','Celular') !!}
                    	{!! Form::text('celular',$client->celular,['class'=>'form-control', 'disabled']) !!}
	                </div>
				</div>
			</div>

			<div>
				<ticket-prices
					:ticket-types="{{ $ticketTypes }}"
					:events="{{ $events }}"
				/>
			</div>

			<div class="row">
				<div class="col-xl-3">
	                <div class="form-group">
	                    {!! Form::label('method_pay_id','Metodo de pago') !!}
                    	{!! Form::select('method_pay_id',$methodPays,'',['class'=>'form-control form-control-alt', 'placeholder'=>'Seleccione...']) !!}
	                </div>
				</div>
				<div class="col-xl-9">
	                <div class="form-group">
	                    {!! Form::label('ref','Referencia') !!}
                    	{!! Form::text('ref',null,['class'=>'form-control',]) !!}
	                </div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-6 col-xl-5">
	                <div class="form-group">
	                    <a href="{{ route('client.index') }}" class='btn btn-danger' data-toggle='tooltip' data-placement='top' title='Regresar' data-original-title='Top Tooltip' role='button'> Regresar </a>
                    	<button type="submit" class="btn btn-primary">Guardar</button>
	                </div>
				</div>
			</div>
		{{ Form::close() }}
            
    </div>
    
@endsection

resources/views/tickets/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="card-header text-white bg-primary">
    Tickets
    </div>
    <div class="card-body">
        <h5 class="card-title">Listado de tickets</h5>

        <a class="btn btn-primary" href="{{ Route('client.index') }}" role="button">Nuevo</a>

        <h4 class="m-4"><strong>Filtros</strong></h4>
        {!! Form::open(['route'=>'ticket.index', 'method'=>'GET', 'class' => 'form-inline m-2']) !!}

        <div class="form-group mx-sm-3 mb-2">
            {!! Form::label('search','Busqueda') !!}
            {!! Form::text('search',null,['class'=>'form-control ml-2', 'placeholder'=>'Busqueda']) !!}
        </div>
        <button type="submit" class="btn btn-primary btn-flat mb-2" data-toggle="tooltip" data-placement="top" title="Buscar"><i class="fa fa-search"></i></button>

        {!! Form::close() !!}

        <table class="table table-bordered table-striped table-vcenter">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Evento</th>
                    <th scope="col">Documento</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Metodo pago</th>
                    <th scope="col">Referencia</th>
                    <th scope="col">Vendido por</th>
                    <th scope="col">Fecha venta</th>
                    <th scope="col">Checkin</th>
                    <th scope="col">Acción</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $value)
                    <tr>
                        <th scope="row">{{ $value->id }}</th>
                        <td>{{ $value->event->name }}</td>
                        <td>{{ $value->client->document }}</td>
                        <td>{{ $value->client->name }}</td>
                        <td>{{ $value->methodPay->name }}</td>
                        <td>{{ $value->ref }}</td>
                        <td>{{ $value->user->name }}</td>
                        <td>{{ $value->created_at }}</td>
                        <td>
                            @if(!$value->checkin_at)
                                <span class="badge badge-success">Sin chequear</span>
                            @else
                                <span class="badge badge-danger">Chequeado</span>
                            @endif
                        </td>
                        <td>
                            <span class="badge badge-default">
                                <a href="{{ Route('ticket.reprint', $value) }}" class="btn btn-sm btn-success" data-toggle="tooltip" data-placement="top" title="Reimprimir ticket" data-original-title="Top Tooltip" target="_blank">
                                    <i class="fa fa-print" aria-hidden="true"></i>
                                </a>

                                <a href="#" class="btn btn-sm btn-warning" data-toggle="tooltip" data-placement="top" title="Cambiar Status" data-original-title="Top Tooltip" onclick="return confirm('Seguro que desea cambiar checkin?...')">
                                    <i class="fa fa-code-branch" aria-hidden="true"></i>
                                </a>
                                @if(Auth::user()->isAdmin())
                                    <a href="{{ Route('ticket.destroy', $value) }}" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top" title="Anular" data-original-title="Top Tooltip" onclick="return confirm('Seguro que desea anular?...')">
                                        <i class="fa fa-times" aria-hidden="true"></i>
                                    </a>
                                @endif
                            </span>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        {{ $data->appends(Request::query())->links() }}
    </div>


    
@endsection

resources/views/tickets/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="card-header text-white bg-primary">
    Tickets
    </div>
    <div class="card-body">
        <h5 class="card-title">Mostrar Ticket</h5>

        @if(!$ticket->checkin_at)
        	<div class="alert alert-success" role="alert">CheckIn disponible</div>
       	@else
       		<div class="alert alert-danger" role="alert">Checkin Realizado</div>
        @endif

        {!! Form::open(['route'=>['ticket.checkin',$ticket], 'method'=>'POST', 'class'=> 'mb-5']) !!}
			<div class="row">
				<div class="col-lg-4 col-xl-5">
					{!! Form::hidden('client_id',$ticket->client->id,[]) !!}
					{!! Form::hidden('serial',Request()->get('serial'),[]) !!}
					{!! Form::hidden('event_id',Request()->get('event'),[]) !!}
	                <div class="form-group">
	                    {!! Form::label('name','Nombre completo') !!}
	                    {!! Form::text('name',$ticket->client->name,['class'=>'form-control','disabled']) !!}
	                </div>
				</div>
				<div class="col-lg-4 col-xl-5">
	                <div class="form-group">
	                    {!! Form::label('email','Correo electronico') !!}
	                    {!! Form::email('email',$ticket->client->email,['class'=>'form-control', 'disabled']) !!}
	                </div>
				</div>
				<div class="col-lg-4 col-xl-2">
	                <div class="form-group">
	                    {!! Form::label('document','Documento de identificacion') !!}
                    	{!! Form::text('document',$ticket->client->document,['class'=>'form-control', 'disabled']) !!}
	                </div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-4 col-xl-5">
	                <div class="form-group">
	                    {!! Form::label('address','Direccion') !!}
                    	{!! Form::text('address',$ticket->client->address,['class'=>'form-control', 'disabled']) !!}
	                </div>
				</div>
				<div class="col-lg-4 col-xl-5">
	                <div class="form-group">
	                    {!! Form::label('phone','Telefono') !!}
                    	{!! Form::text('phone',$ticket->client->phone,['class'=>'form-control', 'disabled']) !!}
	                </div>
				</div>
				<div class="col-lg-4 col-xl-2">
	                <div class="form-group">
	                    {!! Form::label('celular','Celular') !!}
                    	{!! Form::text('celular',$ticket->client->celular,['class'=>'form-control', 'disabled']) !!}
	                </div>
				</div>
			</div>


			<div class="row">
				<div class="col-xl-6">
	                <div class="form-group">
	                	{!! Form::label('event_id','Evento') !!}
                    	{!! Form::text('event_id',$ticket->event->name,['class'=>'form-control', 'disabled']) !!}
	                </div>
				</div>
				<div class="col-xl-6">
	                <div class="form-group">
	                	{!! Form::label('ticket_type_id','Evento') !!}
                    	{!! Form::text('ticket_type_id',$ticket->ticketType->full_name,['class'=>'form-control', 'disabled']) !!}
	                </div>
				</div>
			</div>

			<div class="row">
				<div class="col-xl-3">
	                <div class="form-group">
	                	{!! Form::label('method_pay_id','Metodo de pago') !!}
                    	{!! Form::text('method_pay_id',$ticket->methodPay->name,['class'=>'form-control', 'disabled']) !!}
	                </div>
				</div>
				<div class="col-xl-9">
	                <div class="form-group">
	                    {!! Form::label('ref','Referencia') !!}
                    	{!! Form::text('ref',$ticket->ref,['class'=>'form-control', 'disabled']) !!}
	                </div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-6 col-xl-5">
	                <div class="form-group">
	                    <a href="{{ route('client.index') }}" class='btn btn-danger' data-toggle='tooltip' data-placement='top' title='Regresar' data-original-title='Top Tooltip' role='button'> Regresar </a>
	                    @if( (Auth::user()->isOperator() || Auth::user()->isAdmin()) && !$ticket->checkin_at)
                    		<button type="submit" class="btn btn-success" onclick="return confirm('Seguro que desea hacer checkin?...')">Checkin</button>
                    	@endif
	                </div>
				</div>
			</div>
		{{ Form::close() }}
            
    </div>
    
@endsection